title: Sipeng Zheng
description: PhD student of Renmin University of China
site_title: '@zsp - Sipeng Zheng'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: zhengsipeng
blog_url: https://www.nagekar.com
email: zhengsipeng@ruc.edu.cn
keybase_username: zsp
twitter_username: zsp
reddit_username: zsp

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 